name: Build ML Pipeline

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-model:
    runs-on: ubuntu-latest

    steps:
      - name: Install Signate CLI
        run: pip install signate

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2  # 必要に応じて東京リージョン等に変更

      - name: Run pipeline
        run: python tennis-pipe-line/pipeline.py
